rethinkdb:
  image: rethinkdb
  restart: always
  ports:
    - "8080"
    - "28015"
    - "29015"
discovery:
  image: microbox/etcd:latest
  restart: always
  command: -name discovery
  ports:
    - "4001:4001"
    - "7001:7001"
proxy:
  image: shipyard/docker-proxy:latest
  restart: always
  hostname: default
  environment:
    - PORT=2375
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - "2375:2375"
swarm-manager:
  image: swarm:latest
  restart: always
  command: manage --host tcp://0.0.0.0:3375 etcd://discovery:4001
  links:
    - "discovery:discovery"
  ports:
    - "2375"
swarm-agent:
  image: swarm:latest
  restart: always
  command: join --addr 10.0.2.15:2375 etcd://10.0.2.15:4001
  links:
    - "discovery:discovery"
  ports:
    - "2375"
controller:
  image: shipyard/shipyard:latest
  restart: always
  command: server -d tcp://swarm:2375
  links:
    - rethinkdb:rethinkdb
    - swarm-manager:swarm
  ports:
    - "8080:8080"